version: '3'

services:
  database:
    image: postgres
    container_name: "toorin-database"
    environment:
      - POSTGRES_DB=tooring
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
    ports:
      - '5432:5432'
    volumes:
      - ./database:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
